# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85863392aa9a2f9c85ac572f133ca74395e1a01022c4860ab81b1f92f4b8d839aac0f9166b959fd45597377745a0283b7022c468863f3e76ca48192f717f3405

test:
  secret_key_base: 4a027d2583a5971b1c9cb677f51b7a6b8c88c4c82259225ff25ebc86f97a01ac6c05981289755e6a624e5d443c1b853d3dea99da1aefee4fd0fab41d99f54815

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
